version: "3.8"

services:
  api:
    build: .
    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - cache
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  postgres_data:
  cache:
      driver: local