# Generated by Django 4.2.1 on 2023-06-02 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_notifications", "0002_alter_stocknotification_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknotification",
            name="last_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocknotification",
            name="notification_interval_min",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="stocknotification",
            name="max_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stocknotification",
            name="min_value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
